import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";
=======
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/component/Navbar";
>>>>>>> 3f31b618e627b117f5778ffab5b3b529932a5bf9

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
<<<<<<< HEAD
=======
          <Navbar />
>>>>>>> 3f31b618e627b117f5778ffab5b3b529932a5bf9
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
